// put definitions here

#include <TH1F.h>
#include <vector>
// histograms
/*
TH1F *ptPhotonGEN_, *ptPhotonREC_; 
TH1F *DeltaRGENREC_;

TH1F *Nvtx_;
TH1F *nPhotons_;
TH1F *nJets_;
TH1F *ptPhoton_, *etaPhoton_, *phiPhoton_, photonPassConversionVeto_, ;
TH1F *ptjet1_, *etajet1_, *phijet1_;
*/

TH1F  //*ptPhotonGEN_, *ptPhotonREC_, *DeltaRGENREC_, 
			*nPhotonsGEN_,
			*photonPtGEN_,
			*photonEtaGEN_,
			*photonPhiGEN_,
			*photonEGEN_,
			*nJetsGEN_,
			*jetPtGEN_1_,
			*jetEtaGEN_1_,
			*jetPhiGEN_1_,
			*jetEGEN_1_,
			*HTGEN_,
			*HTParSum_,
			*Nvtx_, 
			*nPhotons_,
			*isPhotonlead_,
			*photonPt_1_,
			*photonE_1_,
			*photonEta_1_, 
			*photonPhi_1_, 
			*photonBit_1_,
			*photonPassConversionVeto_1_, 
			*photonPfIsoChargedHad_1_, 
			*photonPfIsoNeutralHad_1_, 
			*photonPfIsoPhoton_1_, 
			*photonPfIsoPhotons03ForCic_1_, 
			*photonPfIsoNeutrals03ForCic_1_, 
			*photonPfIsoCharged03ForCicVtx0_1_,
			*photonPfIsoCharged03BadForCic_1_, 
			*photonPfIsoPhotons04ForCic_1_, 
			*photonPfIsoNeutrals04ForCic_1_,
			*photonPfIsoCharged04ForCicVtx0_1_, 
			*photonPfIsoCharged04BadForCic_1_,
			*photonid_sieie_1_,  
			*photonid_sieip_1_, 
			*photonid_etawidth_1_, 
			*photonid_phiwidth_1_, 
			*photonid_r9_1_, 
			*photonid_lambdaRatio_1_, 
			*photonid_s4Ratio_1_,
			*photonid_e25_1_, 
			*photonid_sceta_1_, 
			*photonid_ESEffSigmaRR_1_, 
			*photonid_hadronicOverEm_1_, 
			*photonid_hadronicOverEm2012_1_,
			*photonhcalTowerSumEtConeDR04_1_, 
			*photonecalRecHitSumEtConeDR04_1_, 
			*photonnTrkSolidConeDR04_1_,
			*photontrkSumPtSolidConeDR04_1_, 
			*photonnTrkHollowConeDR04_1_, 
			*photontrkSumPtHollowConeDR04_1_, 
			//PhotonIso_1_,
			*photonIsoFPRCharged_1_, 
			*photonIsoFPRNeutral_1_, 
			*photonIsoFPRPhoton_1_, /**jetPhotonDPhi_,*/ 
			*nJets_, 
			*jetPt_1_, 
			*jetEta_1_, 
			*jetY_1_,
			*jetPhi_1_, 
			*jetE_1_,
			*jetPt_2_, 
			*jetEta_2_, 
			*jetY_2_,
			*jetPhi_2_, 
			*jetE_2_,
			*jetPt_3_, 
			*jetEta_3_, 
			*jetY_3_,
			*jetPhi_3_, 
			*jetE_3_,
			*DeltaR_photon1_jet1_,
			*DeltaEta_photon1_jet1_,
			*DeltaPhi_photon1_jet1_,
			*DeltaR_photon1_jet2_,
			*DeltaR_jet1_jet2_,
			*DeltaEta_jet1_jet2_,
			*DeltaPhi_jet1_jet2_,				
			*DeltaR_photon1_jet3_,
			*HT_;
			
//  ptPhoton_->Sumw2();
//  etaPhoton_->Sumw2();
//  phiPhoton_->Sumw2();

void Book_Histos();
void Plot_Histos();
void Zero_Variables();
void Text_File();
float deltaEta(float, float);
//float deltaPhi(float, float);
//float deltaR(float, float, float, float);

// variables
Float_t weight_r, weight_withPU_r;
string  sample_r;
Long64_t nentries_r;
Char_t  outputname[100];
Char_t  textname[100];
Int_t		isPhotonlead, photonBit_1;
Float_t //GENjet1, etaGENjet1,
				//PhotonGEN_, *ptPhotonREC_, *DeltaRGENREC_, 
				nPhotonsGEN,
				jetPtGEN_1,							
				jetEtaGEN_1,
				jetPhiGEN_1,
				jetEGEN_1,
				nJetsGEN,
				HTGEN,
				HTParSum,				
				Nvtx, 
				nPhotons,
				photonPt_1,
				photonE_1,
				photonEta_1, 
				photonPhi_1, 
				photonPassConversionVeto_1, 
				photonPfIsoChargedHad_1, 
				photonPfIsoNeutralHad_1, 
				photonPfIsoPhoton_1, 
				photonPfIsoPhotons03ForCic_1, 
				photonPfIsoNeutrals03ForCic_1, 
				photonPfIsoCharged03ForCicVtx0_1,
				photonPfIsoCharged03BadForCic_1, 
				photonPfIsoPhotons04ForCic_1, 
				photonPfIsoNeutrals04ForCic_1,
				photonPfIsoCharged04ForCicVtx0_1, 
				photonPfIsoCharged04BadForCic_1,
				photonid_sieie_1,  
				photonid_sieip_1, 
				photonid_etawidth_1, 
				photonid_phiwidth_1, 
				photonid_r9_1, 
				photonid_lambdaRatio_1, 
				photonid_s4Ratio_1,
				photonid_e25_1, 
				photonid_sceta_1, 
				photonid_ESEffSigmaRR_1, 
				photonid_hadronicOverEm_1, 
				photonid_hadronicOverEm2012_1,
				photonhcalTowerSumEtConeDR04_1, 
				photonecalRecHitSumEtConeDR04_1, 
				photonnTrkSolidConeDR04_1,
				photontrkSumPtSolidConeDR04_1, 
				photonnTrkHollowConeDR04_1, 
				photontrkSumPtHollowConeDR04_1, 
				//PhotonIso_1,
				photonIsoFPRCharged_1, 
				photonIsoFPRNeutral_1, 
				photonIsoFPRPhoton_1,
				/**jetPhotonDPhi_,*/ 
				nJets, 
				jetPt_1, 
				jetEta_1, 
				jetY_1,
				jetPhi_1, 
				jetE_1,
				jetPt_2, 
				jetEta_2, 
				jetY_2,
				jetPhi_2, 
				jetE_2,
				jetPt_3, 
				jetEta_3, 
				jetY_3,
				jetPhi_3, 
				jetE_3,				
				DeltaR_photon1_jet1,
				DeltaEta_photon1_jet1,				
				DeltaPhi_photon1_jet1,
				DeltaR_photon1_jet2,
				DeltaR_jet1_jet2,				
				DeltaEta_jet1_jet2,
				DeltaPhi_jet1_jet2,				
				DeltaR_photon1_jet3,
				HT;
				
//counters
Int_t  iSelected0, iSelected1, iSelected2, iSelected3, iSelected4, iSelected5, iSelected6, iSelected7; 
Int_t  iSelectedWithWeights0, iSelectedWithWeights1, iSelectedWithWeights2, iSelectedWithWeights3, iSelectedWithWeights4, iSelectedWithWeights5, iSelectedWithWeights6, iSelectedWithWeights7;
//clean
//unsigned int jetN, iJetar, iJetcl, conta, conta1;

// #### cleaning new: jet vs. ALL photons - start
vector<float>	jetPt_cl_new_ALL,
							jetEta_cl_new_ALL, 
							jetPhi_cl_new_ALL,
							jetE_cl_new_ALL; 

TH1F  //*ptPhotonGEN_cl_new_ALL_, *ptPhotonREC_cl_new_ALL_, *DeltaRGENREC_cl_new_ALL_, 
			*Nvtx_cl_new_ALL_, 
			*nPhotons_cl_new_ALL_,
			*isPhotonlead_cl_new_ALL_,
			*photonPt_1_cl_new_ALL_,
			*photonE_1_cl_new_ALL_,
			*photonEta_1_cl_new_ALL_, 
			*photonPhi_1_cl_new_ALL_, 
			*photonBit_1_cl_new_ALL_,
			*photonPassConversionVeto_1_cl_new_ALL_, 
			*photonPfIsoChargedHad_1_cl_new_ALL_, 
			*photonPfIsoNeutralHad_1_cl_new_ALL_, 
			*photonPfIsoPhoton_1_cl_new_ALL_, 
			*photonPfIsoPhotons03ForCic_1_cl_new_ALL_, 
			*photonPfIsoNeutrals03ForCic_1_cl_new_ALL_, 
			*photonPfIsoCharged03ForCicVtx0_1_cl_new_ALL_,
			*photonPfIsoCharged03BadForCic_1_cl_new_ALL_, 
			*photonPfIsoPhotons04ForCic_1_cl_new_ALL_, 
			*photonPfIsoNeutrals04ForCic_1_cl_new_ALL_,
			*photonPfIsoCharged04ForCicVtx0_1_cl_new_ALL_, 
			*photonPfIsoCharged04BadForCic_1_cl_new_ALL_,
			*photonid_sieie_1_cl_new_ALL_,  
			*photonid_sieip_1_cl_new_ALL_, 
			*photonid_etawidth_1_cl_new_ALL_, 
			*photonid_phiwidth_1_cl_new_ALL_, 
			*photonid_r9_1_cl_new_ALL_, 
			*photonid_lambdaRatio_1_cl_new_ALL_, 
			*photonid_s4Ratio_1_cl_new_ALL_,
			*photonid_e25_1_cl_new_ALL_, 
			*photonid_sceta_1_cl_new_ALL_, 
			*photonid_ESEffSigmaRR_1_cl_new_ALL_, 
			*photonid_hadronicOverEm_1_cl_new_ALL_, 
			*photonid_hadronicOverEm2012_1_cl_new_ALL_,
			*photonhcalTowerSumEtConeDR04_1_cl_new_ALL_, 
			*photonecalRecHitSumEtConeDR04_1_cl_new_ALL_, 
			*photonnTrkSolidConeDR04_1_cl_new_ALL_,
			*photontrkSumPtSolidConeDR04_1_cl_new_ALL_, 
			*photonnTrkHollowConeDR04_1_cl_new_ALL_, 
			*photontrkSumPtHollowConeDR04_1_cl_new_ALL_, 
			//PhotonIso_1_cl_new_ALL_,
			*photonIsoFPRCharged_1_cl_new_ALL_, 
			*photonIsoFPRNeutral_1_cl_new_ALL_, 
			*photonIsoFPRPhoton_1_cl_new_ALL_, /**jetPhotonDPhi_,*/ 
			*nJets_cl_new_ALL_, 
			*jetPt_1_cl_new_ALL_, 
			*jetEta_1_cl_new_ALL_, 
			*jetY_1_cl_new_ALL_,
			*jetPhi_1_cl_new_ALL_, 
			*jetE_1_cl_new_ALL_,
			*jetPt_2_cl_new_ALL_, 
			*jetEta_2_cl_new_ALL_, 
			*jetY_2_cl_new_ALL_,
			*jetPhi_2_cl_new_ALL_, 
			*jetE_2_cl_new_ALL_,
			*jetPt_3_cl_new_ALL_, 
			*jetEta_3_cl_new_ALL_, 
			*jetY_3_cl_new_ALL_,
			*jetPhi_3_cl_new_ALL_, 
			*jetE_3_cl_new_ALL_,
			*DeltaR_photon1_jet1_cl_new_ALL_,
			*DeltaEta_photon1_jet1_cl_new_ALL_,			
			*DeltaPhi_photon1_jet1_cl_new_ALL_,
			*DeltaR_photon1_jet2_cl_new_ALL_,
			*DeltaR_jet1_jet2_cl_new_ALL_,
			*DeltaEta_jet1_jet2_cl_new_ALL_,
			*DeltaPhi_jet1_jet2_cl_new_ALL_,				
			*DeltaR_photon1_jet3_cl_new_ALL_,
			*HT_cl_new_ALL_;

Int_t nJets_cl_new_ALL;
Float_t jetPt_1_cl_new_ALL,
				jetEta_1_cl_new_ALL,
				jetY_1_cl_new_ALL,
				jetPhi_1_cl_new_ALL,
				jetE_1_cl_new_ALL,
				jetPt_2_cl_new_ALL,
				jetEta_2_cl_new_ALL,
				jetY_2_cl_new_ALL,
				jetPhi_2_cl_new_ALL,
				jetE_2_cl_new_ALL,
				jetPt_3_cl_new_ALL,
				jetEta_3_cl_new_ALL,
				jetY_3_cl_new_ALL,
				jetPhi_3_cl_new_ALL,
				jetE_3_cl_new_ALL,
				DeltaR_photon1_jet1_cl_new_ALL,
				DeltaEta_photon1_jet1_cl_new_ALL,				
				DeltaPhi_photon1_jet1_cl_new_ALL, 
				DeltaR_photon1_jet2_cl_new_ALL, 
				DeltaR_jet1_jet2_cl_new_ALL, 
				DeltaEta_jet1_jet2_cl_new_ALL, 
				DeltaPhi_jet1_jet2_cl_new_ALL, 
				DeltaR_photon1_jet3_cl_new_ALL, 
				HT_cl_new_ALL;

Int_t  iSelected0_cl_new_ALL, iSelected1_cl_new_ALL, iSelected2_cl_new_ALL, iSelected3_cl_new_ALL, iSelected4_cl_new_ALL, iSelected5_cl_new_ALL, iSelected6_cl_new_ALL, iSelected7_cl_new_ALL, TruephotonsN; 
Int_t  iSelectedWithWeights0_cl_new_ALL, iSelectedWithWeights1_cl_new_ALL, iSelectedWithWeights2_cl_new_ALL, iSelectedWithWeights3_cl_new_ALL, iSelectedWithWeights4_cl_new_ALL, iSelectedWithWeights5_cl_new_ALL, iSelectedWithWeights6_cl_new_ALL, iSelectedWithWeights7_cl_new_ALL;
// #### cleaning new: jet vs. ALL photons - finish

// #### cleaning new: jet vs. LEADING photon - start
vector<float>	Truephoton_Pt,
							Truephoton_Eta,
							Truephoton_Phi,
							Truephoton_E,
							jetPt_cl_new_LEA,
							jetEta_cl_new_LEA, 
							jetPhi_cl_new_LEA,
							jetE_cl_new_LEA; 

TH1F  //*ptPhotonGEN_cl_new_LEA_, *ptPhotonREC_cl_new_LEA_, *DeltaRGENREC_cl_new_LEA_, 
			*Nvtx_cl_new_LEA_, 
			*nPhotons_cl_new_LEA_,
			*isPhotonlead_cl_new_LEA_,
			*photonPt_1_cl_new_LEA_,
			*photonE_1_cl_new_LEA_,
			*photonEta_1_cl_new_LEA_, 
			*photonPhi_1_cl_new_LEA_, 
			*photonBit_1_cl_new_LEA_,
			*photonPassConversionVeto_1_cl_new_LEA_, 
			*photonPfIsoChargedHad_1_cl_new_LEA_, 
			*photonPfIsoNeutralHad_1_cl_new_LEA_, 
			*photonPfIsoPhoton_1_cl_new_LEA_, 
			*photonPfIsoPhotons03ForCic_1_cl_new_LEA_, 
			*photonPfIsoNeutrals03ForCic_1_cl_new_LEA_, 
			*photonPfIsoCharged03ForCicVtx0_1_cl_new_LEA_,
			*photonPfIsoCharged03BadForCic_1_cl_new_LEA_, 
			*photonPfIsoPhotons04ForCic_1_cl_new_LEA_, 
			*photonPfIsoNeutrals04ForCic_1_cl_new_LEA_,
			*photonPfIsoCharged04ForCicVtx0_1_cl_new_LEA_, 
			*photonPfIsoCharged04BadForCic_1_cl_new_LEA_,
			*photonid_sieie_1_cl_new_LEA_,  
			*photonid_sieip_1_cl_new_LEA_, 
			*photonid_etawidth_1_cl_new_LEA_, 
			*photonid_phiwidth_1_cl_new_LEA_, 
			*photonid_r9_1_cl_new_LEA_, 
			*photonid_lambdaRatio_1_cl_new_LEA_, 
			*photonid_s4Ratio_1_cl_new_LEA_,
			*photonid_e25_1_cl_new_LEA_, 
			*photonid_sceta_1_cl_new_LEA_, 
			*photonid_ESEffSigmaRR_1_cl_new_LEA_, 
			*photonid_hadronicOverEm_1_cl_new_LEA_, 
			*photonid_hadronicOverEm2012_1_cl_new_LEA_,
			*photonhcalTowerSumEtConeDR04_1_cl_new_LEA_, 
			*photonecalRecHitSumEtConeDR04_1_cl_new_LEA_, 
			*photonnTrkSolidConeDR04_1_cl_new_LEA_,
			*photontrkSumPtSolidConeDR04_1_cl_new_LEA_, 
			*photonnTrkHollowConeDR04_1_cl_new_LEA_, 
			*photontrkSumPtHollowConeDR04_1_cl_new_LEA_, 
			//PhotonIso_1_cl_new_LEA_,
			*photonIsoFPRCharged_1_cl_new_LEA_, 
			*photonIsoFPRNeutral_1_cl_new_LEA_, 
			*photonIsoFPRPhoton_1_cl_new_LEA_, /**jetPhotonDPhi_,*/ 
			*nJets_cl_new_LEA_, 
			*jetPt_1_cl_new_LEA_, 
			*jetEta_1_cl_new_LEA_, 
			*jetY_1_cl_new_LEA_,
			*jetPhi_1_cl_new_LEA_, 
			*jetE_1_cl_new_LEA_,
			*jetPt_2_cl_new_LEA_, 
			*jetEta_2_cl_new_LEA_, 
			*jetY_2_cl_new_LEA_,
			*jetPhi_2_cl_new_LEA_, 
			*jetE_2_cl_new_LEA_,
			*jetPt_3_cl_new_LEA_, 
			*jetEta_3_cl_new_LEA_, 
			*jetY_3_cl_new_LEA_,
			*jetPhi_3_cl_new_LEA_, 
			*jetE_3_cl_new_LEA_,
			*DeltaR_photon1_jet1_cl_new_LEA_,
			*DeltaEta_photon1_jet1_cl_new_LEA_,			
			*DeltaPhi_photon1_jet1_cl_new_LEA_,
			*DeltaR_photon1_jet2_cl_new_LEA_,
			*DeltaR_jet1_jet2_cl_new_LEA_,
			*DeltaEta_jet1_jet2_cl_new_LEA_,
			*DeltaPhi_jet1_jet2_cl_new_LEA_,				
			*DeltaR_photon1_jet3_cl_new_LEA_,
			*HT_cl_new_LEA_;

Int_t nJets_cl_new_LEA;
Float_t jetPt_1_cl_new_LEA,
				jetEta_1_cl_new_LEA,
				jetY_1_cl_new_LEA,
				jetPhi_1_cl_new_LEA,
				jetE_1_cl_new_LEA,
				jetPt_2_cl_new_LEA,
				jetEta_2_cl_new_LEA,
				jetY_2_cl_new_LEA,
				jetPhi_2_cl_new_LEA,
				jetE_2_cl_new_LEA,
				jetPt_3_cl_new_LEA,
				jetEta_3_cl_new_LEA,
				jetY_3_cl_new_LEA,
				jetPhi_3_cl_new_LEA,
				jetE_3_cl_new_LEA,
				DeltaR_photon1_jet1_cl_new_LEA,
				DeltaEta_photon1_jet1_cl_new_LEA,				
				DeltaPhi_photon1_jet1_cl_new_LEA, 
				DeltaR_photon1_jet2_cl_new_LEA, 
				DeltaR_jet1_jet2_cl_new_LEA, 
				DeltaEta_jet1_jet2_cl_new_LEA, 
				DeltaPhi_jet1_jet2_cl_new_LEA, 
				DeltaR_photon1_jet3_cl_new_LEA, 
				HT_cl_new_LEA;

Int_t  iSelected0_cl_new_LEA, iSelected1_cl_new_LEA, iSelected2_cl_new_LEA, iSelected3_cl_new_LEA, iSelected4_cl_new_LEA, iSelected5_cl_new_LEA, iSelected6_cl_new_LEA, iSelected7_cl_new_LEA; 
Int_t  iSelectedWithWeights0_cl_new_LEA, iSelectedWithWeights1_cl_new_LEA, iSelectedWithWeights2_cl_new_LEA, iSelectedWithWeights3_cl_new_LEA, iSelectedWithWeights4_cl_new_LEA, iSelectedWithWeights5_cl_new_LEA, iSelectedWithWeights6_cl_new_LEA, iSelectedWithWeights7_cl_new_LEA;
// #### cleaning new: jet vs. LEADING photon - finish

// #### cleaning new: photon class - start
vector<float>	jetPt_True,
							jetEta_True, 
							jetPhi_True,
							jetE_True; 

TH1F  //*ptPhotonGEN_True_, *ptPhotonREC_True_, *DeltaRGENREC_True_, 
			*nPhotons_True_,
			*photonPt_1_True_,
			*photonE_1_True_,
			*photonEta_1_True_, 
			*photonPhi_1_True_, 
			*nJets_True_, 
			*jetPt_1_True_, 
			*jetEta_1_True_, 
			*jetPhi_1_True_, 
			*jetE_1_True_,
			*jetPt_2_True_, 
			*jetEta_2_True_, 
			*jetY_2_True_,
			*jetPhi_2_True_, 
			*jetE_2_True_,
			*jetPt_3_True_, 
			*jetEta_3_True_, 
			*jetY_3_True_,
			*jetPhi_3_True_, 
			*jetE_3_True_,
			*DeltaR_photon1_jet1_True_,
			*DeltaEta_photon1_jet1_True_,			
			*DeltaPhi_photon1_jet1_True_,
			*DeltaR_photon1_jet2_True_,
			*DeltaR_jet1_jet2_True_,
			*DeltaEta_jet1_jet2_True_,
			*DeltaPhi_jet1_jet2_True_,				
			*DeltaR_photon1_jet3_True_,
			*HT_True_;

Int_t nJets_True;
Float_t jetPt_1_True,
				jetEta_1_True,
				jetY_1_True,
				jetPhi_1_True,
				jetE_1_True,
				jetPt_2_True,
				jetEta_2_True,
				jetY_2_True,
				jetPhi_2_True,
				jetE_2_True,
				jetPt_3_True,
				jetEta_3_True,
				jetY_3_True,
				jetPhi_3_True,
				jetE_3_True,
				DeltaR_photon1_jet1_True,
				DeltaEta_photon1_jet1_True,				
				DeltaPhi_photon1_jet1_True, 
				DeltaR_photon1_jet2_True, 
				DeltaR_jet1_jet2_True, 
				DeltaEta_jet1_jet2_True, 
				DeltaPhi_jet1_jet2_True, 
				DeltaR_photon1_jet3_True, 
				HT_True;

Int_t  iSelected0_True, iSelected1_True, iSelected2_True, iSelected3_True, iSelected4_True, iSelected5_True, iSelected6_True, iSelected7_True; 
Int_t  iSelectedWithWeights0_True, iSelectedWithWeights1_True, iSelectedWithWeights2_True, iSelectedWithWeights3_True, iSelectedWithWeights4_True, iSelectedWithWeights5_True, iSelectedWithWeights6_True, iSelectedWithWeights7_True;
// #### cleaning new: photon class - finish




// #### cleaning old - start
vector<float>	jetPt_cl_old,
							jetEta_cl_old, 
							jetPhi_cl_old,
							jetE_cl_old; 

TH1F  //*ptPhotonGEN_cl_old_, *ptPhotonREC_cl_old_, *DeltaRGENREC_cl_old_, 
			*Nvtx_cl_old_, 
			*nPhotons_cl_old_,
			*isPhotonlead_cl_old_,
			*photonPt_1_cl_old_,
			*photonE_1_cl_old_,
			*photonEta_1_cl_old_, 
			*photonPhi_1_cl_old_, 
			*photonBit_1_cl_old_,
			*photonPassConversionVeto_1_cl_old_, 
			*photonPfIsoChargedHad_1_cl_old_, 
			*photonPfIsoNeutralHad_1_cl_old_, 
			*photonPfIsoPhoton_1_cl_old_, 
			*photonPfIsoPhotons03ForCic_1_cl_old_, 
			*photonPfIsoNeutrals03ForCic_1_cl_old_, 
			*photonPfIsoCharged03ForCicVtx0_1_cl_old_,
			*photonPfIsoCharged03BadForCic_1_cl_old_, 
			*photonPfIsoPhotons04ForCic_1_cl_old_, 
			*photonPfIsoNeutrals04ForCic_1_cl_old_,
			*photonPfIsoCharged04ForCicVtx0_1_cl_old_, 
			*photonPfIsoCharged04BadForCic_1_cl_old_,
			*photonid_sieie_1_cl_old_,  
			*photonid_sieip_1_cl_old_, 
			*photonid_etawidth_1_cl_old_, 
			*photonid_phiwidth_1_cl_old_, 
			*photonid_r9_1_cl_old_, 
			*photonid_lambdaRatio_1_cl_old_, 
			*photonid_s4Ratio_1_cl_old_,
			*photonid_e25_1_cl_old_, 
			*photonid_sceta_1_cl_old_, 
			*photonid_ESEffSigmaRR_1_cl_old_, 
			*photonid_hadronicOverEm_1_cl_old_, 
			*photonid_hadronicOverEm2012_1_cl_old_,
			*photonhcalTowerSumEtConeDR04_1_cl_old_, 
			*photonecalRecHitSumEtConeDR04_1_cl_old_, 
			*photonnTrkSolidConeDR04_1_cl_old_,
			*photontrkSumPtSolidConeDR04_1_cl_old_, 
			*photonnTrkHollowConeDR04_1_cl_old_, 
			*photontrkSumPtHollowConeDR04_1_cl_old_, 
			//PhotonIso_1_cl_old_,
			*photonIsoFPRCharged_1_cl_old_, 
			*photonIsoFPRNeutral_1_cl_old_, 
			*photonIsoFPRPhoton_1_cl_old_, /**jetPhotonDPhi_,*/ 
			*nJets_cl_old_, 
			*jetPt_1_cl_old_, 
			*jetEta_1_cl_old_, 
			*jetY_1_cl_old_,
			*jetPhi_1_cl_old_, 
			*jetE_1_cl_old_,
			*jetPt_2_cl_old_, 
			*jetEta_2_cl_old_, 
			*jetY_2_cl_old_,
			*jetPhi_2_cl_old_, 
			*jetE_2_cl_old_,
			*jetPt_3_cl_old_, 
			*jetEta_3_cl_old_, 
			*jetY_3_cl_old_,
			*jetPhi_3_cl_old_, 
			*jetE_3_cl_old_,
			*DeltaR_photon1_jet1_cl_old_,
			*DeltaEta_photon1_jet1_cl_old_,			
			*DeltaPhi_photon1_jet1_cl_old_,
			*DeltaR_photon1_jet2_cl_old_,
			*DeltaR_jet1_jet2_cl_old_,
			*DeltaEta_jet1_jet2_cl_old_,
			*DeltaPhi_jet1_jet2_cl_old_,				
			*DeltaR_photon1_jet3_cl_old_,
			*HT_cl_old_;

Int_t nJets_cl_old;
Float_t jetPt_1_cl_old,
				jetEta_1_cl_old,
				jetY_1_cl_old,
				jetPhi_1_cl_old,
				jetE_1_cl_old,
				jetPt_2_cl_old,
				jetEta_2_cl_old,
				jetY_2_cl_old,
				jetPhi_2_cl_old,
				jetE_2_cl_old,
				jetPt_3_cl_old,
				jetEta_3_cl_old,
				jetY_3_cl_old,
				jetPhi_3_cl_old,
				jetE_3_cl_old,
				DeltaR_photon1_jet1_cl_old,
				DeltaEta_photon1_jet1_cl_old,
				DeltaPhi_photon1_jet1_cl_old, 
				DeltaR_photon1_jet2_cl_old, 
				DeltaR_jet1_jet2_cl_old, 
				DeltaEta_jet1_jet2_cl_old, 
				DeltaPhi_jet1_jet2_cl_old, 
				DeltaR_photon1_jet3_cl_old, 
				HT_cl_old;

Int_t  iSelected0_cl_old, iSelected1_cl_old, iSelected2_cl_old, iSelected3_cl_old, iSelected4_cl_old, iSelected5_cl_old, iSelected6_cl_old, iSelected7_cl_old; 
Int_t  iSelectedWithWeights0_cl_old, iSelectedWithWeights1_cl_old, iSelectedWithWeights2_cl_old, iSelectedWithWeights3_cl_old, iSelectedWithWeights4_cl_old, iSelectedWithWeights5_cl_old, iSelectedWithWeights6_cl_old, iSelectedWithWeights7_cl_old;
// #### cleaning old - finish
