// put definitions here

#include <TH1F.h>
#include <vector>
#include <TLorentzVector.h>

void Zero_Variables();
//void Book_Histos();
//void Plot_Histos();
//void Text_File();
float deltaEta(float, float);


// variables
Float_t weight_r, weight_withPU_r;
string sample_r;
Long64_t nentries_r;
Char_t outputname[100];
Char_t textname[100];

Float_t photonPfIso,
				photonPfIso_ov_Pt,
				photonIsoFPRCharged_ov_Pt,
				photonIsoFPRNeutral_ov_Pt,
				photonIsoFPRPhoton_ov_Pt;

Float_t	CleanedJetsGEN_N,
				CleanedJetsGEN_HT,
				SelectedJetsGEN_N,
				SelectedJetsGEN_HT,
				IDIsoPhotons_N,
				SelectedPhotons_N,
				CleanedJetsLEA_N,
				SelectedJetsLEA_N,
				CleanedJets_N,
				SelectedJets_N,
				nPhotonsGEN,
				jetPtGEN_1,
				jetEtaGEN_1,
				jetPhiGEN_1,
				jetEGEN_1,
				nJetsGEN,
				HTGEN,
				HTParSum,
				DeltaR_photon1_jet1_N0,
				DeltaEta_photon1_jet1_N0,
				DeltaPhi_photon1_jet1_N0,
				DeltaPhi_photon1_jet1_N1,
				DeltaR_photon1_jet2_N1,
				DeltaR_jet1_jet2_N1,
				DeltaEta_jet1_jet2_N1,
				DeltaPhi_jet1_jet2_N1,
				DeltaPhi_photon1_jet1_N2,
				DeltaPhi_photon1_jet2_N2,
				DeltaPhi_photon1_jet3_N2,
				DeltaR_photon1_jet3_N2,
				DeltaPhi_jet1_jet2_N2,
				DeltaPhi_jet1_jet3_N2,
				DeltaPhi_jet2_jet3_N2,
				CleanedJets_HT,
				SelectedJets_HT;

vector<float> CleanedJetsGEN_Pt,
							SelectedJetsGEN_Pt,
							SelectedJetsGEN_Eta,
							SelectedJetsGEN_Phi,
							SelectedJetsGEN_E,
							SelectedPhotons_Pt,
							SelectedPhotons_Eta,
							SelectedPhotons_Phi,
							SelectedPhotons_E,
							SelectedPhotons_PassConversionVeto,
							SelectedPhotons_PfIsoChargedHad,
							SelectedPhotons_PfIsoNeutralHad,
							SelectedPhotons_PfIsoPhoton,
							SelectedPhotons_PfIso,
							SelectedPhotons_PfIso_ov_Pt,
							SelectedPhotons_PfIsoPhotons03ForCic,
							SelectedPhotons_PfIsoNeutrals03ForCic,
							SelectedPhotons_PfIsoCharged03ForCicVtx0,
							SelectedPhotons_PfIsoCharged03BadForCic,
							SelectedPhotons_PfIsoPhotons04ForCic,
							SelectedPhotons_PfIsoNeutrals04ForCic,
							SelectedPhotons_PfIsoCharged04ForCicVtx0,
							SelectedPhotons_PfIsoCharged04BadForCic,
							SelectedPhotons_id_sieie,
							SelectedPhotons_id_sieip,
							SelectedPhotons_id_etawidth,
							SelectedPhotons_id_phiwidth,
							SelectedPhotons_id_r9,
							SelectedPhotons_id_lambdaRatio,
							SelectedPhotons_id_s4Ratio,
							SelectedPhotons_id_e25,
							SelectedPhotons_id_sceta,
							SelectedPhotons_id_ESEffSigmaRR,
							SelectedPhotons_id_hadronicOverEm,
							SelectedPhotons_id_hadronicOverEm2012,
							SelectedPhotons_hcalTowerSumEtConeDR04,
							SelectedPhotons_ecalRecHitSumEtConeDR04,
							SelectedPhotons_nTrkSolidConeDR04,
							SelectedPhotons_trkSumPtSolidConeDR04,
							SelectedPhotons_nTrkHollowConeDR04,
							SelectedPhotons_trkSumPtHollowConeDR04,
							SelectedPhotons_IsoFPRCharged,
							SelectedPhotons_IsoFPRNeutral,
							SelectedPhotons_IsoFPRPhoton,
							SelectedPhotons_IsoFPRCharged_ov_Pt,
							SelectedPhotons_IsoFPRNeutral_ov_Pt,
							SelectedPhotons_IsoFPRPhoton_ov_Pt,
							SelectedPhotons_Bit,
							SelectedPhotons_TeP_SF,
							CleanedJets_Pt,
							SelectedJets_Pt,
							SelectedJets_Eta,
							SelectedJets_Phi,
							SelectedJets_E;

vector<float> SelectedPhotons_ScaleFactors;

vector<TLorentzVector> vPtEtaPhiE;
vector<double> myEvshpV,
							 TA;
vector<int> Grouping,
						Grouping_test;

Float_t phiTA,
				dphi_TA_BAxis,
				dphi_TA_J1Axis,
				thrust,
				broad,
				S3,
				S4,
				ln_thrust,
				ln_broad,
				ln_S3,
				ln_S4;

// histograms
TH1F *nPhotonsGEN_,
		 *photonPtGEN_,
		 *photonEtaGEN_,
		 *photonPhiGEN_,
		 *photonEGEN_,
		 *CleanedJetsGEN_N_,
		 *SelectedJetsGEN_N_,
		 *SelectedJets_PtGEN_1_,
		 *SelectedJets_EtaGEN_1_,
		 *SelectedJets_PhiGEN_1_,
		 *SelectedJets_EGEN_1_,
		 *CleanedJetsGEN_HT_,
		 *SelectedJetsGEN_HT_,
		 *HTParSum_,
		 *pre_photonIsoPtDR03GEN_,
		 *IDIsoPhotons_N_,
		 *SelectedPhotons_N_,
		 *Nvtx_,
		 *SelectedPhotons_Pt_1_,
		 *SelectedPhotons_E_1_,
		 *SelectedPhotons_Eta_1_,
		 *SelectedPhotons_Phi_1_,
		 *SelectedPhotons_Bit_1_,
		 *SelectedPhotons_TeP_SF_1_,
		 *SelectedPhotons_PassConversionVeto_1_,
		 *SelectedPhotons_PfIsoChargedHad_1_,
		 *SelectedPhotons_PfIsoNeutralHad_1_,
		 *SelectedPhotons_PfIsoPhoton_1_,
		 *SelectedPhotons_PfIso_1_,
		 *SelectedPhotons_PfIso_ov_Pt_1_,
		 *SelectedPhotons_PfIsoPhotons03ForCic_1_,
		 *SelectedPhotons_PfIsoNeutrals03ForCic_1_,
		 *SelectedPhotons_PfIsoCharged03ForCicVtx0_1_,
		 *SelectedPhotons_PfIsoCharged03BadForCic_1_,
		 *SelectedPhotons_PfIsoPhotons04ForCic_1_,
		 *SelectedPhotons_PfIsoNeutrals04ForCic_1_,
		 *SelectedPhotons_PfIsoCharged04ForCicVtx0_1_,
		 *SelectedPhotons_PfIsoCharged04BadForCic_1_,
		 *SelectedPhotons_id_sieie_1_,
		 *SelectedPhotons_id_sieip_1_,
		 *SelectedPhotons_id_etawidth_1_,
		 *SelectedPhotons_id_phiwidth_1_,
		 *SelectedPhotons_id_r9_1_,
		 *SelectedPhotons_id_lambdaRatio_1_,
		 *SelectedPhotons_id_s4Ratio_1_,
		 *SelectedPhotons_id_e25_1_,
		 *SelectedPhotons_id_sceta_1_,
		 *SelectedPhotons_id_ESEffSigmaRR_1_,
		 *SelectedPhotons_id_hadronicOverEm_1_,
		 *SelectedPhotons_id_hadronicOverEm2012_1_,
		 *SelectedPhotons_hcalTowerSumEtConeDR04_1_,
		 *SelectedPhotons_ecalRecHitSumEtConeDR04_1_,
		 *SelectedPhotons_nTrkSolidConeDR04_1_,
		 *SelectedPhotons_trkSumPtSolidConeDR04_1_,
		 *SelectedPhotons_nTrkHollowConeDR04_1_,
		 *SelectedPhotons_trkSumPtHollowConeDR04_1_,
		 *SelectedPhotons_IsoFPRCharged_1_,
		 *SelectedPhotons_IsoFPRNeutral_1_,
		 *SelectedPhotons_IsoFPRPhoton_1_,
		 *SelectedPhotons_IsoFPRCharged_ov_Pt_1_,
		 *SelectedPhotons_IsoFPRNeutral_ov_Pt_1_,
		 *SelectedPhotons_IsoFPRPhoton_ov_Pt_1_,
		 *CleanedJetsLEA_N_,
		 *SelectedJetsLEA_N_,
		 *CleanedJets_N_,
		 *SelectedJets_N_,
		 *SelectedJets_Pt_1_,
		 *SelectedJets_Eta_1_,
		 *SelectedJets_Phi_1_,
		 *SelectedJets_E_1_,
		 *CleanedJets_HT_,
		 *SelectedJets_HT_,
		 *thrust_N0_,
		 *broad_N0_,
		 *S3_N0_,
		 *S4_N0_,
		 *ln_thrust_N0_,
		 *ln_broad_N0_,
		 *ln_S3_N0_,
		 *ln_S4_N0_,
		 *DeltaR_photon1_jet1_N0_,
		 *DeltaEta_photon1_jet1_N0_,
		 *DeltaPhi_photon1_jet1_N0_,
		 *SelectedJets_Pt_2_,
		 *SelectedJets_Eta_2_,
		 *SelectedJets_Phi_2_,
		 *SelectedJets_E_2_,
		 *DeltaPhi_photon1_jet1_N1_,
		 *DeltaR_photon1_jet2_N1_,
		 *DeltaR_jet1_jet2_N1_,
		 *DeltaEta_jet1_jet2_N1_,
		 *DeltaPhi_jet1_jet2_N1_,
		 *SelectedJets_Pt_3_,
		 *SelectedJets_Eta_3_,
		 *SelectedJets_Phi_3_,
		 *SelectedJets_E_3_,
		 *DeltaPhi_photon1_jet1_N2_,
		 *DeltaPhi_photon1_jet2_N2_,
		 *DeltaPhi_photon1_jet3_N2_,
		 *DeltaR_photon1_jet3_N2_,
		 *DeltaPhi_jet1_jet2_N2_,
		 *DeltaPhi_jet1_jet3_N2_,
		 *DeltaPhi_jet2_jet3_N2_,
		 *CleanedJetsLEA_preHT_N_,
		 *SelectedJetsLEA_preHT_N_,
		 *CleanedJets_preHT_N_,
		 *SelectedJets_preHT_N_,
		 *SelectedJets_preHT_Pt_1_,
		 *SelectedJets_preHT_Pt_2_,
		 *SelectedJets_preHT_Pt_3_,
		 *CleanedJets_preHT_HT_,
		 *SelectedJets_preHT_HT_,
		 *photonIsoPtDR03GEN_;

Int_t iSelected0, iSelected1, iSelected2, iSelected3, iSelected4;
// Int_t iSelectedWithWeights0, iSelectedWithWeights1, iSelectedWithWeights2, iSelectedWithWeights3, iSelectedWithWeights4;
// #### cleaning new: photon class - finish
