/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyPdf_background_1.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyPdf_background_1) 

 RooMyPdf_background_1::RooMyPdf_background_1(const char *name, const char *title, 
                        RooAbsReal& _y,
                        RooAbsReal& _alpha,
                        RooAbsReal& _beta) :
   RooAbsPdf(name,title), 
   y("y","y",this,_y),
   alpha("alpha","alpha",this,_alpha),
   beta("beta","beta",this,_beta)
 { 
 } 


 RooMyPdf_background_1::RooMyPdf_background_1(const RooMyPdf_background_1& other, const char* name) :  
   RooAbsPdf(other,name), 
   y("y",this,other.y),
   alpha("alpha",this,other.alpha),
   beta("beta",this,other.beta)
 { 
 } 



 Double_t RooMyPdf_background_1::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return (1 - exp(alpha*(y-beta)));
 } 



