/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYPDF_BACKGROUND_1
#define ROOMYPDF_BACKGROUND_1

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyPdf_background_1 : public RooAbsPdf {
public:
  RooMyPdf_background_1() {} ; 
  RooMyPdf_background_1(const char *name, const char *title,
	      RooAbsReal& _y,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta);
  RooMyPdf_background_1(const RooMyPdf_background_1& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPdf_background_1(*this,newname); }
  inline virtual ~RooMyPdf_background_1() { }

protected:

  RooRealProxy y ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyPdf_background_1,1) // Your description goes here...
};
 
#endif
