/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOMYPDF_BACKGROUND_2
#define ROOMYPDF_BACKGROUND_2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooMyPdf_background_2 : public RooAbsPdf {
public:
  RooMyPdf_background_2() {} ; 
  RooMyPdf_background_2(const char *name, const char *title,
	      RooAbsReal& _y,
	      RooAbsReal& _alpha,
	      RooAbsReal& _beta,
	      RooAbsReal& _gamma);
  RooMyPdf_background_2(const RooMyPdf_background_2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooMyPdf_background_2(*this,newname); }
  inline virtual ~RooMyPdf_background_2() { }

protected:

  RooRealProxy y ;
  RooRealProxy alpha ;
  RooRealProxy beta ;
  RooRealProxy gamma ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooMyPdf_background_2,1) // Your description goes here...
};
 
#endif
